In [1]:
import numpy as np
#task1, task2 
file = open('sentense.txt', 'r')
data=[]
for line in file.readlines():
    data.append(line.lower())

In [2]:
#task3
import re
nd=[]
for line in data:
    nd.append(re.split('[^a-z]', line))
for line in nd:
    while '' in line:
        line.remove('')

In [3]:
all_words = []
for line in nd:
    for word in line:
        if word in all_words:
            continue
        else:
            all_words.append(word)

In [4]:
def get_unique_words(all_words):
    unique_words = []
    for word in all_words:
        if word in unique_words:
            continue
        else:
            unique_words.append(word)
    return unique_words

len(get_unique_words(all_words))

254

In [5]:
#task4
arr = np.array(nd)
w={}
unique_words = get_unique_words(all_words)
for word in unique_words:
    w[word] = len(unique_words)
    unique_words.remove(word)



In [6]:
#task5
array = np.zeros((22,254))
for i in range(len(nd)):
    for j in range(len(unique_words)):
        array[i][j] = nd[i].count(unique_words[j])

In [7]:
#task6
from scipy.spatial import distance
dist = np.empty([22,1])
for i in range(len(array)):
    dist[i] = distance.cosine(array[0], array[i])


In [8]:
sorted(dist)

[array([0.]),
 array([0.77207885]),
 array([0.78178211]),
 array([0.79796949]),
 array([0.80481999]),
 array([0.83096915]),
 array([0.85714286]),
 array([0.85714286]),
 array([0.86636938]),
 array([0.87401184]),
 array([0.88603942]),
 array([0.88603942]),
 array([0.89517152]),
 array([0.89517152]),
 array([0.89898475]),
 array([0.89898475]),
 array([0.91091292]),
 array([0.92587507]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.])]

In [10]:
from scipy.spatial.distance import cosine
import re
import numpy as np


def word_count(word, line):
    result = 0
    for w in line:
        if w == word:
            result = result + 1
    return result


def get_lines_and_words(file):
    result_lines, result_words = [], []
    with open(file, 'r') as f:
        raw_lines = f.readlines()

    for line in raw_lines:
        line = line.lower()
        split_words = [x for x in re.split('[^a-z]', line) if x != '']
        result_lines.append(split_words)
        result_words.extend(split_words)

    result_words = set(result_words)
    result_words = dict(zip([x for x in range(len(result_words))], result_words))
    return result_lines, result_words


def set_matrix(lines, words):
    result = np.zeros((len(lines), len(words)))
    for i in range(len(lines)):
        for j in range(len(words)):
            result[i, j] = word_count(words[j], lines[i])

    return result


def get_distincts(matrix, startV):
    result = {}
    
    for i in range(0, startV):
        result[i] = cosine(matrix[startV,], matrix[i])
    
    for i in range(startV + 1, len(matrix)):
        result[i] = cosine(matrix[startV,], matrix[i])

    return result      
    

LINES, WORDS = get_lines_and_words("sentense.txt")
C = set_matrix(LINES, WORDS)
RES_DIC = get_distincts(C, 0)
RES_SORT = sorted(RES_DIC.items(), key=lambda x: x[1])
print(RES_SORT[0][0], RES_SORT[1][0])

6 4
